[workspace]
resolver = "2"
members = ["crates/*", "examples"]

[workspace.package]
authors = [
  "Matt Green <matt@denormalized.io>",
  "Amey Chaugule <amey@denormalized.io>",
]
edition = "2021"
homepage = "https://github.com/probably-nothing-labs/df-streams"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/probably-nothing-labs/df-streams"
version = "0.1.0"

[workspace.dependencies]
datafusion = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-common = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-expr = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-franz = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-functions = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-functions-aggregate = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-optimizer = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-physical-expr = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-sql = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }
datafusion-execution = { git = "https://github.com/probably-nothing-labs/arrow-datafusion" }

df-streams-core = { path = "crates/core" }
df-streams-sinks = { path = "crates/sinks" }

arrow = { version = "52.0.0", features = ["prettyprint"] }
arrow-schema = { version = "52.0.0", default-features = false }
futures = "0.3"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"
tokio = { version = "1.36", features = ["macros", "rt", "sync"] }
serde = { version = "1", features = ["derive"] }
async-trait = "0.1.81"
rdkafka = "0.36.2"
log = "^0.4"
